version: 0.0.{build}

image: Visual Studio 2017

configuration: Release

services:
  - mssql2016
  
before_build:
  - nuget restore
  - dotnet ef database update --project C:\projects\tsd-pokerplanning\PlanningPokerBackend\
